version: '3'

services:
  webserver:
    image: nginx:alpine
    restart: always
    ports:
     - "80:80"
    volumes:
     - ./photos:/var/www/html
     - ./default.conf:/etc/nginx/conf.d/default.conf


  webp:
    image: webpsh/webp-server-go
    # image: ghcr.io/webp-sh/webp_server_go
    restart: always
    environment:
      - MALLOC_ARENA_MAX=1
      # - LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so.2
      # - LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libtcmalloc_minimal.so.4.5.6
      # - READ_BUFFER_SIZE=4096
      # - CONCURRENCY=262144
      # - DISABLE_KEEPALIVE=false
    volumes:
      - ./photos:/opt/pics
      - ./config.json:/etc/config.json
#      - ./path/to/exhaust:/opt/exhaust
#      - ./path/to/metadata:/opt/metadata
    ports:
      - "3333:3333"
    deploy:
      resources:
        limits:
          memory: 400M
    memswap_limit: 400M